import 'package:flutter/material.dart';
import '../models/health_milestone.dart';

final List<HealthMilestone> healthMilestones = [
  HealthMilestone(
    id: '20min',
    titleKey: 'bloodPressureHeartRateDrop',
    descriptionKey: 'heartRateBloodPressureDesc',
    minutesAfterQuit: 20,
    icon: Icons.favorite,
    category: 'cardiovascular',
    color: Colors.red,
    bgColor: Colors.red.shade50,
  ),
  HealthMilestone(
    id: '8hours',
    titleKey: 'carbonMonoxideNormalize',
    descriptionKey: 'carbonMonoxideDesc',
    minutesAfterQuit: 8 * 60,
    icon: Icons.air,
    category: 'respiratory',
    color: Colors.blue,
    bgColor: Colors.blue.shade50,
  ),
  HealthMilestone(
    id: '24hours',
    titleKey: 'heartAttackRiskDecrease',
    descriptionKey: 'heartAttackRiskDesc',
    minutesAfterQuit: 24 * 60,
    icon: Icons.shield,
    category: 'cardiovascular',
    color: Colors.green,
    bgColor: Colors.green.shade50,
  ),
  HealthMilestone(
    id: '72hours',
    titleKey: 'airwaysRelax',
    descriptionKey: 'airwaysDesc',
    minutesAfterQuit: 72 * 60,
    icon: Icons.accessibility_new,
    category: 'respiratory',
    color: Colors.cyan,
    bgColor: Colors.cyan.shade50,
  ),
  HealthMilestone(
    id: '2weeks',
    titleKey: 'circulationImprove',
    descriptionKey: 'circulationDesc',
    minutesAfterQuit: 2 * 7 * 24 * 60,
    icon: Icons.trending_up,
    category: 'circulation',
    color: Colors.purple,
    bgColor: Colors.purple.shade50,
  ),
  HealthMilestone(
    id: '2months',
    titleKey: 'lungsCleanUp',
    descriptionKey: 'lungsDesc',
    minutesAfterQuit: 2 * 30 * 24 * 60,
    icon: Icons.flash_on,
    category: 'metabolic',
    color: Colors.amber,
    bgColor: Colors.amber.shade50,
  ),
  HealthMilestone(
    id: '3months',
    titleKey: 'nervesRegenerate',
    descriptionKey: 'nervesDesc',
    minutesAfterQuit: 3 * 30 * 24 * 60,
    icon: Icons.air,
    category: 'respiratory',
    color: Colors.teal,
    bgColor: Colors.teal.shade50,
  ),
  HealthMilestone(
    id: '10years',
    titleKey: 'lungCancerRiskHalved',
    descriptionKey: 'lungCancerDesc',
    minutesAfterQuit: 10 * 365 * 24 * 60,
    icon: Icons.security,
    category: 'cancer',
    color: Colors.orange,
    bgColor: Colors.orange.shade50,
  ),
];